apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-application
  namespace: argocd
  annotations:
    recipients.argocd-notifications.argoproj.io: slack:#general
spec:
  project: default

  source:
    repoURL: https://github.com/hamadakafu/argocd-sample.git
    targetRevision: master
    path: applications

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  syncPolicy:
    automated: {}

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-cm
#   namespace: argocd
#   labels:
#     app.kubernetes.io/name: argocd-cm
#     app.kubernetes.io/part-of: argocd
# data:
#   # v1.3 or later use `repositories` with `type: helm`
#   repositories: |
#     - type: helm
#       url: https://raw.githubusercontent.com/hamadakafu/sample_helm_chart/master
#       name: hamadakafu
#       usernameSecret:
#         name: my-secret
#         key: username
#       passwordSecret:
#         name: my-secret
#         key: password
#