apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hamadakafu/argocd-sample.git
    targetRevision: dummy-branch
    path: applications

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  syncPolicy:
    automated: {}

