apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # pr = sample nginx private repository
  name: snpr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/hamadakafu/sample_helm_chart/master
    chart: sample_nginx_chart
    targetRevision: 0.2.0
    helm:
      valueFiles:
        - values.yaml

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  syncPolicy:
    automated: {}

