apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-helm-chart
  namespace: argocd
  annotations:
    recipients.argocd-notifications.argoproj.io: slack:#general
spec:
  project: default
  source:
    repoURL: https://github.com/hamadakafu/argocd-sample.git
    targetRevision: master
    path: charts/sample-helm-chart
    helm:
      releaseName: sample-helm-chart

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  syncPolicy:
    automated: {}

