apiVersion: batch/v1
kind: Job
metadata:
  generateName: server-postsync-notify-
  namespace: argocd
  labels:
    app: server
    chart: server-0.1.0
    release: release-name
    heritage: Tiller
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccount: argocd-server
      containers:
        - name: kubectl
          image: kafuhamada/argo-nofify
          env:
            - name: SLACK_WEBHOOK
              value: "https://hooks.slack.com/services/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"
            - name: SLACK_CHANNEL
              value: "#general"
            - name: SLACK_TITLE
              value: "PostSync"
            - name: SLACK_COLOR
              value: "danger"
