apiVersion: batch/v1 
kind: Job
metadata:
  generateName: sample-hogehoge
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1 
  parallelism: 1 
  backoffLimit: 10 
  template:
    spec:
      containers:
        - name: sleep-container
          image: centos:6 
          command: ["echo"] 
          args: ["fack you"]
      restartPolicy: Never
