apiVersion: batch/v1 
kind: Job
metadata:
  generateName: notification-chart-before-
  annotations:
    argocd.argoproj.io/hook: PreSync 
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1 
  parallelism: 1 
  backoffLimit: 10 
  template:
    spec:
      containers:
        - name: echo-container
          image: appropriate/curl:latest
          command: ["curl"] 
          args:
            - "-X" 
            - "POST"
            - "--data-urlencode"
            - "payload={\"channel\": \"#general\", \"username\": \"webhookbot\", \"text\": \"私はnotification-and-podチャートにいるpresyncです\"}"
            - https://hooks.slack.com/services/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
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: notification-chart-after-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: echo-container
          image: appropriate/curl:latest
          command: ["curl"] 
          args:
            - "-X" 
            - "POST"
            - "--data-urlencode"
            - "payload={\"channel\": \"#general\", \"username\": \"webhookbot\", \"text\": \"私はnotification-and-podチャートにいるpostsyncです\"}"
            - https://hooks.slack.com/services/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
      restartPolicy: Never
  backoffLimit: 0
