apiVersion: batch/v1 
kind: Job
metadata:
  generateName: notification-chart-before-
  annotations:
    argocd.argoproj.io/hook: PreSync 
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1 
  parallelism: 1 
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: echo-container
          image: gcr.io/cloud-builders/kubectl
          command: 
            - "/bin/bash"
          args:
            - "/slack/notify.sh"
            - "https://hooks.slack.com/services/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"
            - "#general"
            - "StartSync"
            - "#439FE0"
          volumeMounts:
            - name: config-volume
              mountPath: /slack
      volumes:
        - name: config-volume
          configMap:
            name: notify-configmap
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: notification-chart-after-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1 
  parallelism: 1 
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: echo-container
          image: gcr.io/cloud-builders/kubectl
          command:
            - "/bin/bash"
          args:
            - "/slack/notify.sh"
            - "https://hooks.slack.com/services/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"
            - "#general"
            - "PostSync"
            - "Good"
          volumeMounts:
            - name: config-volume
              mountPath: /slack
      volumes:
        - name: config-volume
          configMap:
            name: notify-configmap
      restartPolicy: Never

---
apiVersion: batch/v1 
kind: Job
metadata:
  generateName: notification-chart-before-
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1 
  parallelism: 1 
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: kubectl get application info
          image: gcr.io/cloud-builders/kubectl
          command:
            - "kubectl"
          args:
            - "get"
            - "-n"
            - "argocd"
            - "applications.argoproj.io"
            - "sample-application"
            - "-o"
            - "json"
            - "> /tmp/argoinfo"
        - name: echo-container
          image: gcr.io/cloud-builders/jq
          command: 
            - "/bin/bash"
          args:
            - "/slack/notify.sh"
            - "https://hooks.slack.com/services/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"
            - "#general"
            - "SyncFail"
            - "Danger"
          volumeMounts:
            - name: config-volume
              mountPath: /slack
      volumes:
        - name: config-volume
          configMap:
            name: notify-configmap
      restartPolicy: Never
