apiVersion: batch/v1 
kind: Job
metadata:
  generateName: presync-
  annotations:
    argocd.argoproj.io/hook: PreSync 
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1 
  parallelism: 1 
  backoffLimit: 1
  template:
    spec:
      serviceAccount: argocd-server
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: kubectl
          image: gcr.io/cloud-builders/kubectl
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo -n "Applicatin: {{ template "notification-and-pod.name" . }}, " >> /shared-data/SLACK_MESSAGE && \
              echo -n "TargetRevision: " >> /shared-data/SLACK_MESSAGE && \
              kubectl get applications.argoproj.io sample-application -n argocd \
              -o jsonpath='{.spec.source.targetRevision}' >> /shared-data/SLACK_MESSAGE

          volumeMounts:
            - name: shared-data
              mountPath: /shared-data

        - name: slack-notify
          image: technosophos/slack-notify
          command: ["/bin/bash", "-c"]
          args:
            - |
              SLACK_MESSAGE=$(cat /shared-data/SLACK_MESSAGE) /slack-notify
          env:
            - name: SLACK_WEBHOOK
              value: "https://hooks.slack.com/services/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"
            - name: SLACK_CHANNEL
              value: "#general"
            - name: SLACK_TITLE
              value: PreSync
            - name: SLACK_COLOR
              value: "#439FE0"
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data


---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: postsync-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1 
  parallelism: 1 
  backoffLimit: 1
  template:
    spec:
      serviceAccount: argocd-server
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: kubectl
          image: gcr.io/cloud-builders/kubectl
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo -n "Applicatin: {{ template "notification-and-pod.name" . }}, " >> /shared-data/SLACK_MESSAGE && \
              echo -n "TargetRevision: " >> /shared-data/SLACK_MESSAGE && \
              kubectl get applications.argoproj.io sample-application -n argocd \
              -o jsonpath='{.spec.source.targetRevision}' >> /shared-data/SLACK_MESSAGE

          volumeMounts:
            - name: shared-data
              mountPath: /shared-data

        - name: slack-notify
          image: technosophos/slack-notify
          command: ["/bin/bash", "-c"]
          args:
            - |
              SLACK_MESSAGE=$(cat /shared-data/SLACK_MESSAGE) /slack-notify
          env:
            - name: SLACK_WEBHOOK
              value: "https://hooks.slack.com/services/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"
            - name: SLACK_CHANNEL
              value: "#general"
            - name: SLACK_TITLE
              value: PostSync
            - name: SLACK_COLOR
              value: Good
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data

---
apiVersion: batch/v1 
kind: Job
metadata:
  generateName: syncfail-
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  completions: 1 
  parallelism: 1 
  backoffLimit: 1
  template:
    spec:
      serviceAccount: argocd-server
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: kubectl
          image: gcr.io/cloud-builders/kubectl
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo -n "Applicatin: {{ template "notification-and-pod.name" . }}, " >> /shared-data/SLACK_MESSAGE && \
              echo -n "TargetRevision: " >> /shared-data/SLACK_MESSAGE && \
              kubectl get applications.argoproj.io sample-application -n argocd \
              -o jsonpath='{.spec.source.targetRevision}' >> /shared-data/SLACK_MESSAGE

          volumeMounts:
            - name: shared-data
              mountPath: /shared-data

        - name: slack-notify
          image: technosophos/slack-notify
          command: ["/bin/bash", "-c"]
          args:
            - |
              SLACK_MESSAGE=$(cat /shared-data/SLACK_MESSAGE) /slack-notify
          env:
            - name: SLACK_WEBHOOK
              value: "https://hooks.slack.com/services/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"
            - name: SLACK_CHANNEL
              value: "#general"
            - name: SLACK_TITLE
              value: SyncFailed
            - name: SLACK_COLOR
              value: Danger
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data

      restartPolicy: Never
