    curl -X POST -d '{"channel": "${channel}", "username": "gheo", "attachments": [{"title": "${title}", "text": "Application: *${APPLICATION}*\nBranch: *$(cat /tmp/argoinfo | jq -r '.spec.source.targetRevision')*"}]}' ${slack_url}
