apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: notify-configmap
data:
  notify.sh: |
    #!/bin/bash
    set -ex

    which jq
    which curl

    slack_url=$1
    channel=$2
    title=$3
    color=$4

    APPLICATION={{ template "notification-and-pod.fullname" . }}

    TARGET_REVISION=$(cat /tmp/argoinfo | jq -r '.spec.source.targetRevision')

    curl -X POST -d '{"channel": "${channel}", "username": "gheo", "attachments": [{"title": "${title}", "text": "Application: *${APPLICATION}*\nBranch: *${TARGET_REVISION}*"}]}' ${slack_url}
